
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Jun 18 15:25:16 BRT 2018
//----------------------------------------------------

package compilador;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int FIMLINHA = 8;
  public static final int SENAO = 4;
  public static final int FECHACHAV = 17;
  public static final int SENAOSE = 3;
  public static final int ESCREVA = 13;
  public static final int ABREPAR = 5;
  public static final int COMPARACAO = 23;
  public static final int ERROR = 21;
  public static final int ABRECHAV = 16;
  public static final int PULA = 22;
  public static final int INTEIRO = 18;
  public static final int ATRIB = 11;
  public static final int STRING = 24;
  public static final int EOF = 0;
  public static final int OPERADOR = 19;
  public static final int error = 1;
  public static final int COMPREPET = 15;
  public static final int FECHAPAR = 6;
  public static final int SE = 2;
  public static final int REPET = 14;
  public static final int VARIAVEL = 20;
  public static final int COMENTARIO = 7;
  public static final int FIM = 10;
  public static final int LEIA = 12;
  public static final int INICIO = 9;
}

