package compilador;

public enum Token {
    SE, SENAOSE, SENAO, ABREPAR, FECHAPAR, COMENTARIO, FIMLINHA, INICIO, FIM, ATRIB, LEIA, ESCREVA,
    REPET, COMPREPET, ABRECHAV, FECHACHAV, INTEIRO, OPERADOR, VARIAVEL, ERROR, PULA, COMPARACAO, STRING
}
